### PR TITLE
Add vline for end of last section, to show where PE file ends and ove…

### PR DESCRIPTION
**Pull request by kevoreilly**
…rlay (appended data) begins.

### CODE REVIEW

**Comment by geekscrapy** [comment]
Cheers! ...Any chance you can make the pull to contrib branch please?

**Comment by kevoreilly** [comment]
Just tried - but that branch is out of date and so the changes won't work. This has still got the bin_proxy not the new parsedbin.

**Comment by geekscrapy** [comment]
Up to date now... Sorry, new to the git collaboration thing. Can you try again, please?

**Comment by kevoreilly** [comment]
Still can't see any updates to the contrib branch - last commit 7 days ago.

**Comment by geekscrapy** [comment]
Should be fine now?

**Comment by kevoreilly** [comment]
Still no change to contrib branch, but now there is a new branch: as_lib - do you want me to submit PR to this branch?

**Comment by kevoreilly** [comment]
I think I still need to close this as it's to the wrong branch, I'll open a new one for the contrib branch.

**Pull request closed without merging**
